export const types = {
  APP_CONFIG: {
    LIGHT_THEME: 'APP_CONFIG/LIGHT_THEME',
    AUTOPLAY: 'APP_CONFIG/AUTOPLAY',
    SEARCH_LOADING: 'APP_CONFIG/SEARCH_LOADING',
    LATEST_LOADING: 'APP_CONFIG/LATEST_LOADING',
    END_LIST_LOADING: 'APP_CONFIG/END_LIST_LOADING',
    EN_LANG: 'APP_CONFIG/EN_LANG',
    APP_INFO: 'APP_CONFIG/APP_INFO',
    FONT_SIZES: 'APP_CONFIG/FONT_SIZES',
    COLL_ITEMS: 'APP_CONFIG/COLL_ITEMS',
    HISTORY_LIST: 'APP_CONFIG/HISTORY_LIST',
    GET_LATEST: 'APP_CONFIG/GET_LATEST',
    LATEST_ERROR: 'APP_CONFIG/LATEST_ERROR',
    GET_SEARCH: 'APP_CONFIG/GET_SEARCH',
    SEARCH_ERROR: 'APP_CONFIG/SEARCH_ERROR',
    SET_VARIABLES: 'APP_CONFIG/SET_VARIABLES',
  },
};
