export const types = {
  APP_CONFIG: {
    GET_LATEST: 'APP_CONFIG/GET_LATEST',
    GET_SEARCH: 'APP_CONFIG/GET_SEARCH',
    GET_IMDB_SEARCH: 'APP_CONFIG/GET_IMDB_SEARCH',
    LATEST_ERROR: 'APP_CONFIG/LATEST_ERROR',
    SEARCH_ERROR: 'APP_CONFIG/SEARCH_ERROR',
    IMDB_SEARCH_ERROR: 'APP_CONFIG/IMDB_SEARCH_ERROR',
  },
};
